// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "e9bf8f69-03b0-49ea-8c94-a6b27b21de5a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1565554758);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1565554878);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1565579478);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1565576118);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1565575998);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1565554638);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1565555118);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1565554998);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 805934);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1565554248);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f7d25574-86cf-42c5-bc67-4e1e3a0b9139}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1565581357972");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1565583137972");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1565579461368");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1565583061368");
user_pref("browser.search.region", "MX");
user_pref("browser.slowStartup.averageTime", 13876);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1565554253);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1565554257845");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.toolbox.selectedTool", "netmonitor");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("devtools.webconsole.filter.net", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "7fa4124a5e4d47859c75b76a58119f7a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 09 Aug 2019 09:59:13 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1565554758);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.privatebrowsing.notification", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{93adb9ed-22c2-4aa1-a3fb-8d90f3a41e9d}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"5.0.2\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3055630f-d570-40e5-9efa-614d751ec7fe\",\"fxmonitor@mozilla.org\":\"e4be91d1-6944-40db-b658-419ebc5f4825\",\"screenshots@mozilla.org\":\"966b12d2-863a-4c55-a454-bb0486af6fb4\",\"webcompat-reporter@mozilla.org\":\"957d6cf8-c512-43e4-8cdd-fd1b8f741259\",\"webcompat@mozilla.org\":\"cb1f49dc-275f-4968-9ef3-00551baf1787\",\"default-theme@mozilla.org\":\"5331a9f9-e7eb-40d3-a3ce-58552a64f14f\",\"google@search.mozilla.org\":\"254d3efe-ffc0-453f-ad76-ca8f813efea7\",\"bing@search.mozilla.org\":\"d32d9342-e52a-42a0-8cdf-050026bf8e93\",\"ddg@search.mozilla.org\":\"86aaca79-f9c7-4d6d-b64c-18604e091200\",\"mercadolibre@search.mozilla.org\":\"d9536f98-0754-4d16-b5b3-49091faf8aa0\",\"wikipedia@search.mozilla.org\":\"bb240f54-4afc-4134-b0df-00a8fbc35935\"}");
user_pref("idle.lastDailyNotification", 1565556092);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1565554274);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1565554273);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{9d3107c9-23d3-43d8-861a-5fca8a0da887}");
user_pref("places.database.lastMaintenance", 1565556092);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "ede8c1b2-2250-4a5b-ad81-4995433ce280");
user_pref("security.sandbox.plugin.tempDirSuffix", "55c83799-7c3e-4fa0-87f1-f8feb869b59f");
user_pref("services.blocklist.pinning.checked", 1565554568);
user_pref("services.settings.clock_skew_seconds", -231);
user_pref("services.settings.last_etag", "\"1565481679319\"");
user_pref("services.settings.last_update_seconds", 1565554869);
user_pref("services.settings.main.cfr-fxa.last_check", 1565554568);
user_pref("services.settings.main.cfr.last_check", 1565554568);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1565554568);
user_pref("services.settings.main.hijack-blocklists.last_check", 1565554568);
user_pref("services.settings.main.language-dictionaries.last_check", 1565554568);
user_pref("services.settings.main.normandy-recipes.last_check", 1565554568);
user_pref("services.settings.main.onboarding.last_check", 1565554568);
user_pref("services.settings.main.sites-classification.last_check", 1565554568);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1565554568);
user_pref("services.settings.security.onecrl.checked", 1565554568);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1565556092);
user_pref("toolkit.startup.last_success", 1565554240);
user_pref("toolkit.telemetry.cachedClientID", "1ec5f37e-ff03-48cc-8ed0-1c505aa17cec");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
